pipelines:
  - name: S_Matrix
    steps:
      - name: matrix_example
        type: Matrix
        stepMode: Bash 
        stepletMultipliers:
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead
          exclude:
            - environmentVariables:
                animal: dog
                mineral: copper
                vegetable: carrot
            - runtime: 
                 type: image
                 image:
                    auto:
                      language: java
                      versions:
                        - 13.0
          runtimes:                         # Runtimes for steplets
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
          
        execution:
          onExecute:
            - echo "I am executing matrix steplet ${steplet_id}"
            - echo "Envs animal= $animal , mineral = $mineral , vegetable = $vegetable"
