
pipelines:
  - name: Pipelines_S_Matrix_0017
    steps:
      - name: S_Matrix_0017
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - env1: one
            - env2: two
          runtimes: 
            type: image                              # optional, only needed if customer
            - image:                  # wants to execute step against
                auto:                 # multiple images
                  language: node
                  version: 10.21.0
            - image:
                auto:
                  language: node
                  version: 12.14.0
        execution:
          onExecute:
            - echo "Hello world"
