pipelines:    
  - name: Pipeline_test_matrix
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
#           nodePool: u18dynamic
#           inputResources:
#             - name: self_repo
        execution:
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/empty/temp
            - save_tests saveTests/correct
            - echo "Passed"
            - popd
      - name: Matrix_Fan_Out_1
        type: FanOut
        configuration:
          inputSteps:
            - name: Normal_Step
        execution:
          onExecute:
            - sleep 10s
            - echo "I am on fan out step"
            - touch fan_out_1.txt
            - set_step_var fan_out value1
            - echo "Fan out working" > fan_out_1.txt
      - name: Matrix_Fan_Out_2
        type: FanOut
        configuration:
          inputSteps:
            - name: Normal_Step
        execution:
          onExecute:
            - sleep 10s
            - echo "I am on fan out step "
            - touch fan_out_2.txt
            - set_step_var fan_out value1
            - echo "Fan out working" > fan_out_2.txt
      - name: matrix_2
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: Matrix_Fan_Out_1
            - name: Matrix_Fan_Out_2
#           inputResources:
#             - name: self_repo
        stepletMultipliers:
          environmentVariables:
            - env1: one
              env2: two
              env3: three
            - env1: changed1
              env2: changed2
            - env1: changed12
              env2: changed23
            - env1: one1
              env2: two2
              env3: three3
            - env1: changed14
              env2: changed25
            - env1: changed126
              env2: changed237
        execution:
          onExecute:
            - echo "I am on matrix step"
            - ls -l ./Matrix_Fan_Out_1
            - 'touch ${steplet_id}_file'
            - 'echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file'
            - >-
              echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >>
              ${steplet_id}_file
            - set_step_var test_key "$(date)"
            - 'set_step_var addresses "https://www.google.com/${env1}/${steplet_id}"'
            - get_step_var Matrix_Fan_Out_1 fan_out
            - ls -l .
      - name: Matrix_Fan_In
        type: FanIn
        configuration:
          inputSteps:
            - name: matrix_2
        execution:
          onExecute:
            - echo "Hello World"
            - ls -l .
            - ls -l ./matrix_2
            - ls -l ./matrix_2/Matrix_Fan_Out_1/
            - get_step_var matrix_2 test_key
            - get_step_var matrix_2 addresses
