
pipelines:
  - name: pipelines_vijay5
    steps:
      - name: test1
        type: PowerShell
        configuration:
          nodePool: win_2019       
        execution:
          onExecute:
            - write-output "hello world"   
            
      - name: test2
        type: Jenkins
        configuration:
          jenkinsJobName: var-pipeline-proj    # Jenkins job/pipeline name. required
          priority: 1
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: jenkins   
          inputSteps:
            - name : test1              
            
          
