
pipelines:
  - name: pipelines_vijay1
    steps:
      - name: test1
        type: Jenkins
        configuration:
          jenkinsJobName: var-pipeline-proj    # Jenkins job/pipeline name. required
          priority: 1
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: jenkins

      - name: test2
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputSteps:
            - name : test1         
        execution:
          onExecute:
            - write-output "hello world"            
            
          
