
# pipelines:
#   - name: pipelines_vijay
#     steps:
#       - name: test1
#         type: Jenkins
#         configuration:
#           jenkinsJobName: var_output_job    # Jenkins job/pipeline name. required
#           priority: 1
#           buildParameters:
#             key1: 1
#             key2: 2
#           integrations:
#             - name: jenkins

#       - name: test2
#         type: Jenkins
#         configuration:
#           jenkinsJobName: var_output_job   # Jenkins job/pipeline name. required
#           priority: 2
#           buildParameters:
#             key1: 1
#             key2: 2
#           integrations:
#             - name: jenkins
#           inputSteps:
#             - name : test1


pipelines:
  - name: Matrix_pipeline
    steps:
      - name: S_Matrix_0012
        type: PreMatrix
          environmentVariables:
            - key1: value1
        execution:
          onExecute:
            - echo "Executing matrix step"
            - set_step_var my_Step value1


      - name: S_Matrix_0012_1
        type: Matrix
        configuration:
          inputSteps:
            - name: S_Matrix_0012
        execution:
          onExecute:
            - echo "Executing Matrix step"
            - text=$( get_step_var S_Matrix_0012 my_Step )
            - |
              [[ "$text" == "value1" ]]
