
pipelines:
  - name: pipelines4
    steps:
      - name: test1
        type: Bash
        configuration:
          integrations:
            - name: jenkins         
        execution:
          onExecute:
            - echo "hello world"

      - name: test2
        type: Jenkins
        configuration:
          jenkinsJobName: basic-api-mb    # Jenkins job/pipeline name. required
          priority: 1
          buildParameters:
            key1: 1
            key2: 2
          integrations:
            - name: jenkins
          inputSteps:
            - name : test1
            
          
