pipelines:
  - name: Pipelines_S_Matrix_0021
    steps:
      - name: S_Matrix_0021
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - env1: one
            - env2: two
          allowFailures:
            - environmentVariables:
                - env1: one
                - env2: two
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 10.21.0

            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 812.17.0
        execution:
          onExecute:
            - echo "Hello world"           
            
          
